#!/bin/bash

# Update pacman
sudo pacman -S
sudo pacman -Syu

# Install yay
pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay-bin.git && cd yay-bin && makepkg -si

# Update yay
yay -Syu --devel

# insall essentials
sudo pacman -S kitty zsh neovim ranger exa bat ripgrep fzf zoxide entr thefuck lazygit lazydocker btop glow light pulseaudio dunst nm-connection-editor pamixer
yay -S hyprland wofi cava eww swww

sudo chmod a+w /sys/class/backlight/*/brightness
